import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import DevNav from "@/app/dev/DevNav";
import ThemeProvider from "@/app/theme/ThemeProvider";

import * as ui from "@/ui/classes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="min-h-screen px-4 py-6">
            <div className={ui.appFrame}>
              {process.env.NODE_ENV === "development" && <DevNav />}
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
